version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      octokit:
        patterns:
          - "@octokit/*"

  - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"